name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install Android packages (API 35)
        run: |
          sdkmanager --install "platform-tools" "cmdline-tools;latest"
          sdkmanager --install "platforms;android-35"
          sdkmanager --install "build-tools;35.0.0"

      - name: Generate Gradle Wrapper (no binary in git)
        env:
          GRADLE_VERSION: "8.13"
        run: |
          curl -sSfL "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" -o gradle.zip
          unzip -q gradle.zip -d "${HOME}/gradle"
          "${HOME}/gradle/gradle-${GRADLE_VERSION}/bin/gradle" wrapper --gradle-version ${GRADLE_VERSION}
          chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v4

      - name: Assemble Debug APK
        run: ./gradlew clean :app:assembleDebug

      - name: Upload Debug APK (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.sha }}
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Prepare release asset
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          mkdir -p dist
          cp app/build/outputs/apk/debug/app-debug.apk dist/SCANNER-EXADECIMAL-debug.apk

      - name: Publish/Update "nightly" Release (debug APK)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/SCANNER-EXADECIMAL-debug.apk
          asset_name: SCANNER-EXADECIMAL-debug.apk
          tag: nightly
          release_name: Nightly Debug
          overwrite: true
          body: "Commit ${{ github.sha }} — APK debug signé (keystore debug)."

  quality:
    needs: apk
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install Android packages (API 35)
        run: |
          sdkmanager --install "platform-tools" "cmdline-tools;latest"
          sdkmanager --install "platforms;android-35"
          sdkmanager --install "build-tools;35.0.0"

      - name: Generate Gradle Wrapper (no binary in git)
        env:
          GRADLE_VERSION: "8.13"
        run: |
          curl -sSfL "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" -o gradle.zip
          unzip -q gradle.zip -d "${HOME}/gradle"
          "${HOME}/gradle/gradle-${GRADLE_VERSION}/bin/gradle" wrapper --gradle-version ${GRADLE_VERSION}
          chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests and lint
        run: ./gradlew :imagequality:testDebugUnitTest :app:lintDebug

      - name: Upload quality reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quality-reports-${{ github.sha }}
          path: |
            imagequality/build/reports/tests/testDebugUnitTest
            app/build/reports/lint/lintDebug
