name: Android CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download Gradle distribution
        run: |
          curl -sSLo gradle.zip https://services.gradle.org/distributions/gradle-8.13-bin.zip
          unzip -q gradle.zip

      - name: Generate Gradle wrapper
        run: |
          ./gradle-8.13/bin/gradle wrapper --gradle-version 8.13
          chmod +x gradlew

      - name: Configure Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 36
          build-tools: 36.0.0

      - name: Cache Gradle data
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build lint and test
        run: ./gradlew clean :app:assembleDebug :app:lintDebug :imagequality:testDebugUnitTest

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Update nightly release asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if ! gh release view nightly >/dev/null 2>&1; then
            gh release create nightly --title "Nightly" --notes "Automated nightly build"
          fi
          gh release upload nightly app/build/outputs/apk/debug/app-debug.apk --clobber
